<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ici</string>
	</array>
	<key>name</key>
	<string>ICI</string>
	<key>patterns</key>
	<array>
    <dict>
      <key>begin</key>
      <string>/\*</string>
      <key>end</key>
      <string>\*/</string>
      <key>name</key>
      <string>comment.block</string>
    </dict>
    <dict>
      <key>match</key>
      <string>//.*$</string>
      <key>name</key>
      <string>comment.line.double-slash</string>
    </dict>
    <dict>
      <key>match</key>
      <string>"([^\\"]|\\"|\\)*"</string>
      <key>name</key>
      <string>string.quoted.double</string>
    </dict>
    <dict>
      <key>match</key>
      <string>'([^\\']|\\'|\\)*'</string>
      <key>name</key>
      <string>string.quoted.single</string>
    </dict>
    <dict>
      <key>match</key>
      <string>#[^#]*#</string>
      <key>name</key>
      <string>string.regexp</string>
    </dict>
    <dict>
      <key>match</key>
      <string>0x[0-9a-fA-F]+|([0-9]+(\.[0-9]*)?|\.[0-9]*)([eE][+-]?[0-9]+)?</string>
      <key>name</key>
      <string>constant.numeric</string>
    </dict>
    <dict>
      <key>match</key>
      <string>/=|/|\$|@|\(|\)|\{|\}|\[|\]|,|~~~|~~=|~~|~|\.|\*=|\*|%=|%|\^=|\^|\+=|\+\+|\+|-&gt;|-=|--|-|&gt;&gt;=|&gt;&gt;|&gt;=|&gt;|&lt;&lt;=|&lt;&lt;|&lt;=|&lt;|==|=|!=|!~|!|&amp;&amp;|&amp;=|&amp;|\|\||\|=|\||;|\?|:\^|:=|:</string>
      <key>name</key>
      <string>keyword.operator</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(case|default|if|else|while|do|forall|in|for|switch|break|continue|return|try|onerror|critsect|waitfor)\b</string>
      <key>name</key>
      <string>keyword.control</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(array|class|struct|module|set|func)\b</string>
      <key>name</key>
      <string>storage.type</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(extern|static|auto)\b</string>
      <key>name</key>
      <string>storage.modifier</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(NULL)\b</string>
      <key>name</key>
      <string>constant.language.null</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(this)\b</string>
      <key>name</key>
      <string>variable.language.this</string>
    </dict>
    <dict>
      <key>match</key>
      <string>[a-zA-Z_][0-9a-zA-Z]*</string>
      <key>name</key>
      <string>variable</string>
    </dict>
  </array>
	<key>scopeName</key>
	<string>source.ici</string>
	<key>uuid</key>
	<string>A1A1F82B-61AE-4304-A352-61D9D59974A0</string>
</dict>
</plist>